#  Dockerfile for  Backend

FROM node:18

# Create App Directory
RUN mkdir -p /app
WORKDIR /app

# Install Dependencies
COPY package*.json ./

RUN npm install 

# Copy app source code
COPY . .

# Exports
EXPOSE 8000

CMD ["npm","run","dev"]